package md5comparehmac;

import hmac.Hmac;
import md5.MD5;

public class Compare {
	public static void main(String[] args) {
		String message = "asdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsdasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsdasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsdasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsasdfdsafsdscafdsafsdafdsafdsffffsfdsfdsfadsfdasfasdfdsafdsafdsfsdafdsafdsafdsafsdafsadffsd";
		for (int i = 0; i < 4; i++) {
			message = message + message;
		}
		System.out.println("message大小" + message.length() + "B");
		System.out.println("message大小" + (message.length() / 1024) + "KB");
		
		long count = 10000;
		
		long start = System.currentTimeMillis();
		for (int i = 0; i < count; i++) {
			MD5.md5(message);
		}
		long end = System.currentTimeMillis();
		long md5Mills = end - start;
		
		start = System.currentTimeMillis();
		for (int i = 0; i < count; i++) {
			Hmac.hmacsha1(Hmac.HMAC_MD5_ALGORITHM, message);
		}
		end = System.currentTimeMillis();
		long hmacMills = end - start;
		
		System.out.println("md5:" + md5Mills);
		System.out.println("hmac:" + hmacMills);
		System.out.println("hmac-md5:" + (hmacMills-md5Mills));
	}
}
